### ISSUE TITLE
Dark mode distorts colours

### ISSUE THREAD

**Issue by gampleman** [dmy/elm.dmy.fr#1]
While the invert effect is quite [neat for some images](https://dark.elm.dmy.fr/packages/gampleman/elm-visualization/latest/Force), it makes others quite wrong. Compare:

<a href="https://dark.elm.dmy.fr/packages/gampleman/elm-visualization/latest/Scale-Color"><img width="613" alt="Screenshot 2020-05-22 at 08 57 39" src="https://user-images.githubusercontent.com/69144/82640156-61a48780-9c0a-11ea-95a9-b2eb3eeacfa1.png"></a>

<a href="https://elm.dmy.fr/packages/gampleman/elm-visualization/latest/Scale-Color"><img width="615" alt="Screenshot 2020-05-22 at 08 57 53" src="https://user-images.githubusercontent.com/69144/82640247-8bf64500-9c0a-11ea-9e59-09604f6d416e.png"></a>

In dark mode the images promise something that the package simply won't deliver.

**Comment by rlefevre** [comment]
Yeah, I'm not sure how to proceed. I did this because some images use transparency and assume a white background, for example https://dark.elm.dmy.fr/packages/elm/browser/latest/Browser-Dom#Viewport and maybe others I can't remember, and because it usually makes reading documentations with images nicer, but I agree that it is really wrong to break colors in some cases like yours (and color palette packages).

**Comment by gampleman** [comment]
What about a hack where if the documented thing doesn't match `/colou?r|pallete/i`, it gets inverted? Typically things where the color matters will have it in either type signature or module/function name.

**Comment by rlefevre** [comment]
For now I have removed the `invert(100%) hue-rotate(180deg)` and just use a white background color to fix transparent images that assume a white background.

**Comment by gampleman** [comment]
Just found this: https://observablehq.com/@mootari/inverted-luminosity

Which could be a good compromise perhaps.

**Comment by rlefevre** [comment]
That's an interesting technique, thank you for the pointer!

It seems to work quite well in some cases:

https://dark.elm.dmy.fr/packages/gampleman/elm-visualization/latest/
![elm-visualization](https://user-images.githubusercontent.com/5399281/98976417-9ccba780-2517-11eb-97c0-f5742ba05b4a.png)

But not so much in others:

https://dark.elm.dmy.fr/packages/ianmackenzie/elm-3d-scene/latest/
![3d-scene-2](https://user-images.githubusercontent.com/5399281/98976621-ddc3bc00-2517-11eb-9c50-86919c2d5b5d.png)
![3d-scene-1](https://user-images.githubusercontent.com/5399281/98976534-c2f14780-2517-11eb-8371-18ef835bdc65.png)

It's strange though that the background becomes grey instead of black, so maybe the filter is not exactly the expected one?

**Comment by gampleman** [comment]
Hm, yeah I guess it was a fun idea, but seems like just leaving images alone (with a white bg) is the most reliable...
